import random
import time
numbers=list(range(1,1000000))
randomadd=list(range(1,1000000))
number = random.choice(numbers)
print(f"warning, {number} dimensional splits.")
time.sleep(2)
print("entering emergency mode.")
time.sleep(.2)
print(".")
time.sleep(.2)
print("..")
time.sleep(.2)
print("...")
time.sleep(.2)
print("emergency mode booted...")
time.sleep(.2)
print("recieving emergency broadcast from \"Alpha Station, Set B\"")
time.sleep(1)
print("Printing Message \"Project Black Eagle has been a catastrophic failure. The dimensions of our world are splitting open, the amount of splits is already irrepairable manually, your computer should have the commands required to fix the splits automatically. Your computer's AI will know what to do, just type HELP and it should help in some way\"")
input1=input("Delta Station Admin: ")
while(input1!="HELP"):
    print("error, command unknown/corrupted/irrelivant")
    input1=input("Delta Station Admin: ")
splits=number+random.choice(randomadd)
print(f"Hello! I am Delta Station's Artifical Intellgence, you can call me DeSAI. Currently there are {splits} dimensional splits, this will now be tracked at the beginning of most outputs with brackets around it, like this: [{splits}], currently only the following commands are functional because the system is booted in emergency mode. []")
